blueprint:
  name: Motion-activated Light or Switch
  description: Turn on a light or switch when motion is detected.
  domain: automation
  source_url: https://github.com/thiagoholder/blueprints/blob/main/motion_light.yaml
  author: Home Assistant
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
    target_entity:
      name: Light or Switch
      description: Select a light or switch to control
      selector:
        entity:
          domain:
            - light
            - switch
    no_motion_wait:
      name: Wait time
      description: Time to leave the light or switch on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"

variables:
  target_entity: !input target_entity
  is_light: "{{ 'light' in target_entity }}"
  is_switch: "{{ 'switch' in target_entity }}"

action:
  - choose:
      - conditions:
          - "{{ is_light }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ target_entity }}"
      - conditions:
          - "{{ is_switch }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ target_entity }}"
  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_entity
        from: "on"
        to: "off"
  - delay: !input no_motion_wait
  - choose:
      - conditions:
          - "{{ is_light }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ target_entity }}"
      - conditions:
          - "{{ is_switch }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: "{{ target_entity }}"
